name: Deploy QA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release Fortum QA
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-git-action-qa"
          heroku_email: "ukalinets@gmail.com"
          branch: "main"
      - name: Release Kotimaan QA
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "second-test-app-qa"
          heroku_email: "ukalinets@gmail.com"
          branch: "main"
